name: iros-training
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=2.5
  - torchvision>=0.20
  - pytorch-cuda=11.8
  - numpy>=1.24
  - pandas>=2.0
  - scipy>=1.10
  - opencv>=4.7
  - pillow>=9.4
  - matplotlib>=3.7
  - tqdm>=4.66
  - pip
  - pip:
      - -e ..
